name: Continuous Integration

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    release:
        types: [ created ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install dependencies
              run: npm ci

            - name: Run test suite
              run: npm run test


    publish:
        needs: build
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'release' }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  registry-url: https://registry.npmjs.org/

            - name: Install dependencies
              run: npm ci

            - name: Run test suite
              run: npm run test

            - name: Set new version
              run: npm version --allow-same-version --no-git-tag-version ${{ github.event.release.tag_name }}

            - name: Publish release
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}